# Generated by Django 2.1.7 on 2019-03-04 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=True, max_length=128, verbose_name='Емейл')),
                ('first_name', models.CharField(default=True, max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(default=True, max_length=128, verbose_name='Фамилия')),
                ('middle_name', models.CharField(default=True, max_length=128, verbose_name='Отчество')),
                ('message', models.TextField(blank=True, default=None, null=True, verbose_name='Сообщение')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата подписки')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
    ]
