# Generated by Django 2.1.7 on 2019-04-08 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Полное описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='В наличии?')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования записи')),
            ],
            options={
                'verbose_name': 'О компании (запись)',
                'verbose_name_plural': 'О компании (запись)',
            },
        ),
        migrations.CreateModel(
            name='About_usImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_us_images/', verbose_name='Фотография')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главная')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуально')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования')),
                ('About_us', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='about_us.About_us', verbose_name='О компании')),
            ],
            options={
                'verbose_name': 'Фотография к вкладке "О компании"',
                'verbose_name_plural': 'Фотографии к вкладкам "О компании"',
            },
        ),
    ]
