# Generated by Django 2.1.7 on 2019-04-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Полное описание кладки "О компании"'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Актуально?'),
        ),
    ]
