# Generated by Django 2.1.7 on 2019-04-08 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Полное вкладки "Гарантии"')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуально?')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования записи')),
            ],
            options={
                'verbose_name': 'Гарантии (запись)',
                'verbose_name_plural': 'Гарантии (запись)',
            },
        ),
    ]
