# Generated by Django 2.1.7 on 2019-04-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantees',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Полное описание вкладки "Гарантии"'),
        ),
    ]
