# Generated by Django 2.1.7 on 2019-03-29 12:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=True, max_length=64, null=True, verbose_name='Наименование мебели')),
                ('short_description', models.TextField(blank=True, default=None, max_length=50, null=True, verbose_name='Кр. описание')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Полное описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='В наличии?')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования записи')),
            ],
            options={
                'verbose_name': 'Мебель',
                'verbose_name_plural': 'Мебель',
            },
        ),
        migrations.CreateModel(
            name='SofaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=True, max_length=128, null=True, verbose_name='Наименование категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуально')),
            ],
            options={
                'verbose_name': 'Категория мебели',
                'verbose_name_plural': 'Категории мебели',
            },
        ),
        migrations.CreateModel(
            name='SofaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sofa_images/', verbose_name='Фотография')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главная')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуально')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования')),
                ('Sofa', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sofas.Sofa', verbose_name='Мебель')),
            ],
            options={
                'verbose_name': 'Фотография мебели',
                'verbose_name_plural': 'Фотографии мебели',
            },
        ),
        migrations.AddField(
            model_name='sofa',
            name='category',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sofas.SofaCategory', verbose_name='Категория мебели'),
        ),
    ]
